max_name_length: 50
max_length_255: 255
min_password_length: 8
min_password_types: 3
valid_email_regex: \A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z
password:
  lowercase: '[a-z]'
  uppercase: '[A-Z]'
  digit: \d
  special: '[^a-zA-Z\d]'
max_ratings: 5
time_zone: Hanoi
date_format: "%d/%m/%Y"
time_format: "%H:%M"
date_time_format: "%H:%M %d/%m/%Y"
hours_expired: 2
min_book_time: 1
image_format: "image/jpeg,image/png"
max_img_size: 5
size_5: 5
limit_img_size: 500
default_password: "*Password123"
sql_time_format: "%H:%M:%S"
